version: "3.9"
services:
  nginx_cert:
    image: nginxproxy/nginx-proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - /etc/nginx/certs
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./infra/conf.d:/etc/nginx/conf.d
  acme:
    image: nginxproxy/acme-companion
    restart: always
    volumes_from:
      - nginx_cert
    volumes:
      - /etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
  donft_backend_ipfs_pure:
    extends:
      file: ./backend/ipfs-pure-service.yaml
      service: donft_ipfs_pure
    environment:
      - PUBLIC_HOST=$IPFS_PURE_URL
      - VIRTUAL_HOST=$IPFS_PURE_URL
      - PASSWORD=$PASSWORD
  ipfs-node-1:
    container_name: ipfs-node-1
    image: ipfs/go-ipfs:latest
    ports:
      - 4001:4001 # ipfs swarm - expose if needed/wanted
      - 5001:5001 # ipfs api - expose if needed/wanted
      - 8080:8080 # ipfs gateway - expose if needed/wanted
    volumes:
      - ./data/ipfs:/data/ipfs
      - ./data/ipfs-staging:/staging
  
