version: "3.9"
services:
  donft_ipfs_pure:
    build:
      context: /root/DoACS/backend/backend/
      dockerfile: ./ipfs_app/Dockerfile
      args:
        buildno: 1
    ports:
      - 5011:5011
    restart: always
    environment:
      - HOST=0.0.0.0
      - PORT=5011
      - IPFS_API_TIMEOUT=20000
      - IPFS_PROJECT_ID=23gzaKecKievdRIjstg7WA4QPoF
      - IPFS_PROJECT_SECRET=83a21969d6bdfd8674b91be42f7799ce
      - IPFS_SERVICE=IPFS
      - IPFS_API_HOST=http://172.21.0.3:5001/api/v0/
      - FILE_NAME_ACCESSES=accesses_pure.txt
    volumes:
      - /root/DoACS/backend/backend:/backend/
      - /root/DoACS/backend/ipfs:/backend/ipfs
